### ISSUE TITLE
kasih superadmin

### ISSUE THREAD

**Issue by hrz8** [subastianSk/BE_Newsate#8]
https://github.com/subastianSk/BE_Newsate/blob/4cce0405981815c1492ad6269bf8ade4994f60db/mixins/common.js#L30

untuk line ini boleh dibuatin gini supaya gak perlu nambahin `superadmin` manual di masing2 `action.authorization`:

```js
 const isRoleExist = ['superadmin', ...ctx.action.authorization].filter((value) => userRoles.includes(value)); 
```

**Comment by subastianSk** [comment]
Done
